export const CREATE_ANIMAL = 'CREATE_ANIMAL';
export const CREATE_ANIMAL_SUCCESSFUL = 'CREATE_ANIMAL_SUCCESSFUL';
export const CREATE_ANIMAL_ERROR = 'CREATE_ANIMAL_ERROR';
export const LIST_ANIMAL = 'LIST_ANIMAL';
export const LIST_SUCCESSFUL_ANIMAL = 'LIST_SUCCESSFUL_ANIMAL';
export const LIST_ANIMAL_ERROR = 'LIST_ANIMAL_ERROR';